In [23]:
import pandas as pd
import numpy as np

In [24]:
dates = pd.date_range(start="2018-01-01", end="2024-12-01", freq='MS')

oil_price = np.cumsum(np.random.normal(0, 2, len(dates))) + 70

shock = np.random.choice(["Normal", "Demand Shock", "Supply Shock"], len(dates))
shock_mag = np.random.randint(-60, 60, len(dates))

oil_df = pd.DataFrame({
    "Date": dates,
    "Oil_Price": oil_price.round(2),
    "Shock_Type": shock,
    "Shock_Magnitude": shock_mag
})

oil_df.to_csv("../data/oil_prices.csv", index=False)

In [25]:
sectors = ["Energy", "Airlines", "Transport", "Manufacturing"]

sector_df = pd.DataFrame({
    "Date": np.repeat(dates, len(sectors)),
    "Sector": sectors * len(dates),
    "Return": np.random.normal(5, 12, len(dates)*len(sectors)).round(2)
})

sector_df.to_csv("../data/sector_data.csv", index=False)

In [26]:
macro_df = pd.DataFrame({
    "Date": dates,
    "Inflation": np.random.uniform(2, 8, len(dates)).round(2),
    "GDP": np.random.uniform(-3, 5, len(dates)).round(2),
    "Interest_Rate": np.random.uniform(3, 8, len(dates)).round(2)
})

macro_df.to_csv("../data/macro_data.csv", index=False)

In [27]:
import pandas as pd

In [28]:
oil_df = pd.read_csv("../data/oil_prices.csv")
sector_df = pd.read_csv("../data/sector_data.csv")
macro_df = pd.read_csv("../data/macro_data.csv")

In [29]:
oil_df['Date'] = pd.to_datetime(oil_df['Date'])
sector_df['Date'] = pd.to_datetime(sector_df['Date'])
macro_df['Date'] = pd.to_datetime(macro_df['Date'])

In [30]:
oil_df.dropna(inplace=True)
sector_df.dropna(inplace=True)
macro_df.dropna(inplace=True)

oil_df.drop_duplicates(inplace=True)
sector_df.drop_duplicates(inplace=True)
macro_df.drop_duplicates(inplace=True)

In [31]:
oil_df['Oil_Return'] = oil_df['Oil_Price'].pct_change()*100

oil_df['Shock_Level'] = oil_df['Shock_Magnitude'].apply(
    lambda x: "High" if abs(x)>40 else "Medium" if abs(x)>20 else "Low"
)

oil_df['Year'] = oil_df['Date'].dt.year
oil_df['Month'] = oil_df['Date'].dt.month

In [32]:
df = oil_df.merge(sector_df, on="Date").merge(macro_df, on="Date")

In [33]:
df.to_csv("cleaned_data.csv", index=False)
df.to_csv("final_dashboard_data.csv", index=False)

In [34]:
df.head()

,Date,Oil_Price,Shock_Type,Shock_Magnitude,Oil_Return,Shock_Level,Year,Month,Sector,Return,Inflation,GDP,Interest_Rate
0,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Energy,10.27,5.19,-1.36,7.7
1,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Airlines,1.41,5.19,-1.36,7.7
2,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Transport,13.24,5.19,-1.36,7.7
3,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Manufacturing,-12.77,5.19,-1.36,7.7
4,2018-02-01,69.12,Normal,59,-3.193277,High,2018,2,Energy,-2.35,7.64,0.95,6.3

In [35]:
df.tail()

,Date,Oil_Price,Shock_Type,Shock_Magnitude,Oil_Return,Shock_Level,Year,Month,Sector,Return,Inflation,GDP,Interest_Rate
331,2024-11-01,75.09,Demand Shock,15,1.185824,Low,2024,11,Manufacturing,12.88,3.93,-2.73,6.23
332,2024-12-01,80.74,Supply Shock,30,7.524304,Medium,2024,12,Energy,11.06,4.10,-1.58,5.44
333,2024-12-01,80.74,Supply Shock,30,7.524304,Medium,2024,12,Airlines,12.05,4.10,-1.58,5.44
334,2024-12-01,80.74,Supply Shock,30,7.524304,Medium,2024,12,Transport,7.02,4.10,-1.58,5.44
335,2024-12-01,80.74,Supply Shock,30,7.524304,Medium,2024,12,Manufacturing,-7.93,4.10,-1.58,5.44

In [36]:
df.columns

Index(['Date', 'Oil_Price', 'Shock_Type', 'Shock_Magnitude', 'Oil_Return',
       'Shock_Level', 'Year', 'Month', 'Sector', 'Return', 'Inflation', 'GDP',
       'Interest_Rate'],
      dtype='object')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             336 non-null    datetime64[ns]
 1   Oil_Price        336 non-null    float64
 2   Shock_Type       336 non-null    object
 3   Shock_Magnitude  336 non-null    int64
 4   Oil_Return       332 non-null    float64
 5   Shock_Level      336 non-null    object
 6   Year             336 non-null    int32
 7   Month            336 non-null    int32
 8   Sector           336 non-null    object
 9   Return           336 non-null    float64
 10  Inflation        336 non-null    float64
 11  GDP              336 non-null    float64
 12  Interest_Rate    336 non-null    float64
dtypes: datetime64[ns](1), float64(6), int32(2), int64(1), object(3)
memory usage: 31.6+ KB

In [38]:
df.isnull().sum()

Date               0
Oil_Price          0
Shock_Type         0
Shock_Magnitude    0
Oil_Return         4
Shock_Level        0
Year               0
Month              0
Sector             0
Return             0
Inflation          0
GDP                0
Interest_Rate      0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df.describe()

,Date,Oil_Price,Shock_Magnitude,Oil_Return,Year,Month,Return,Inflation,GDP,Interest_Rate
count,336,336.000000,336.000000,332.000000,336.000000,336.000000,336.000000,336.000000,336.00000,336.000000
mean,2021-06-16 07:25:42.857142784,65.779762,4.226190,0.198500,2021.000000,6.500000,5.796845,5.091190,1.37119,5.557857
min,2018-01-01 00:00:00,52.300000,-59.000000,-5.299739,2018.000000,1.000000,-32.990000,2.010000,-2.73000,3.020000
25%,2019-09-23 12:00:00,60.022500,-22.000000,-2.277040,2019.000000,3.750000,-1.730000,3.727500,-0.66500,4.150000
50%,2021-06-16 00:00:00,63.495000,3.000000,0.154821,2021.000000,6.500000,5.975000,5.225000,1.18000,5.800000
75%,2023-03-08 18:00:00,72.000000,35.000000,2.628726,2023.000000,9.250000,13.210000,6.475000,3.44750,6.767500
max,2024-12-01 00:00:00,80.740000,59.000000,7.823561,2024.000000,12.000000,43.530000,7.950000,4.95000,7.990000
std,NaN,7.348778,35.683635,3.190437,2.002983,3.457201,11.710097,1.662279,2.36082,1.512284

In [41]:
df.sort_values(by="Date").head(10)

,Date,Oil_Price,Shock_Type,Shock_Magnitude,Oil_Return,Shock_Level,Year,Month,Sector,Return,Inflation,GDP,Interest_Rate
0,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Energy,10.27,5.19,-1.36,7.70
1,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Airlines,1.41,5.19,-1.36,7.70
2,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Transport,13.24,5.19,-1.36,7.70
3,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Manufacturing,-12.77,5.19,-1.36,7.70
4,2018-02-01,69.12,Normal,59,-3.193277,High,2018,2,Energy,-2.35,7.64,0.95,6.30
5,2018-02-01,69.12,Normal,59,-3.193277,High,2018,2,Airlines,9.41,7.64,0.95,6.30
6,2018-02-01,69.12,Normal,59,-3.193277,High,2018,2,Transport,10.35,7.64,0.95,6.30
7,2018-02-01,69.12,Normal,59,-3.193277,High,2018,2,Manufacturing,-4.11,7.64,0.95,6.30
11,2018-03-01,71.29,Supply Shock,2,3.139468,Low,2018,3,Manufacturing,28.88,6.81,-1.19,6.67
10,2018-03-01,71.29,Supply Shock,2,3.139468,Low,2018,3,Transport,15.33,6.81,-1.19,6.67

In [42]:
df['Shock_Level'].unique()

array(['Low', 'High', 'Medium'], dtype=object)

In [43]:
pd.set_option('display.max_columns', None)
df.head(10)

,Date,Oil_Price,Shock_Type,Shock_Magnitude,Oil_Return,Shock_Level,Year,Month,Sector,Return,Inflation,GDP,Interest_Rate
0,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Energy,10.27,5.19,-1.36,7.70
1,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Airlines,1.41,5.19,-1.36,7.70
2,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Transport,13.24,5.19,-1.36,7.70
3,2018-01-01,71.40,Demand Shock,8,NaN,Low,2018,1,Manufacturing,-12.77,5.19,-1.36,7.70
4,2018-02-01,69.12,Normal,59,-3.193277,High,2018,2,Energy,-2.35,7.64,0.95,6.30
5,2018-02-01,69.12,Normal,59,-3.193277,High,2018,2,Airlines,9.41,7.64,0.95,6.30
6,2018-02-01,69.12,Normal,59,-3.193277,High,2018,2,Transport,10.35,7.64,0.95,6.30
7,2018-02-01,69.12,Normal,59,-3.193277,High,2018,2,Manufacturing,-4.11,7.64,0.95,6.30
8,2018-03-01,71.29,Supply Shock,2,3.139468,Low,2018,3,Energy,-4.08,6.81,-1.19,6.67
9,2018-03-01,71.29,Supply Shock,2,3.139468,Low,2018,3,Airlines,2.88,6.81,-1.19,6.67